### ISSUE TITLE
引用块，回车的时候，会多出来一个空行

### ISSUE THREAD

**Issue by jiulu313** [Ben-love-zy/web-editor-markdown#13]

**Comment by jiulu313** [comment]
![image](https://user-images.githubusercontent.com/4046526/201559769-9240665d-0a7b-46f8-940b-433ecfa434fa.png)

如上图

**Comment by Ben-love-zy** [comment]
resolved in v1.0.8

**Comment by jiulu313** [comment]
好的，我看下怎么改的
